server:
  port: 7022
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duweiduwais/authbase-master
          search-paths: config-repo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/